### PR TITLE
feat: dashboard profile

### PR DESCRIPTION
**Pull request by rhmtrz**
This change is [Reviewable](https://reviewable.io/reviews/tigerscave/ada-firebase-auth/25)

### CODE REVIEW

**Review by azamiya — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/tigerscave/ada-firebase-auth/25)* status: all files reviewed, 1 unresolved discussion (waiting on @rhmtrz)

___
*[src/components/anonymatter/my-account/dashboard-profile.js, line 2 at r1](https://reviewable.io/reviews/tigerscave/ada-firebase-auth/25#-LhjPaeS754Ax1AUdB3b:-LhjPaeS754Ax1AUdB3c:bqkse83) ([raw file](https://github.com/tigerscave/ada-firebase-auth/blob/0b31a8f54b7dc6dbd78b44e8ba6c1242932b7c9f/src/components/anonymatter/my-account/dashboard-profile.js#L2)):*
> ```JavaScript
> import React from "react";
> import LogoProfilePanel from "../login/right-side/logo-profile-panel";
> ```

make new component because of style difference.

**Review by azamiya — COMMENTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/tigerscave/ada-firebase-auth/25)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @rhmtrz and @tadaniya)

**Review by azamiya — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tigerscave/ada-firebase-auth/25)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @rhmtrz and @tadaniya)

___
*[src/components/anonymatter/my-account/dashboard-profile.js, line 2 at r1](https://reviewable.io/reviews/tigerscave/ada-firebase-auth/25#-LhjPaeS754Ax1AUdB3b:-LhjVpQ8CG2zgwOnLuKT:b-3yt67o) ([raw file](https://github.com/tigerscave/ada-firebase-auth/blob/0b31a8f54b7dc6dbd78b44e8ba6c1242932b7c9f/src/components/anonymatter/my-account/dashboard-profile.js#L2)):*
<details><summary><i>Previously, tadaniya wrote…</i></summary><blockquote>

make new component because of style difference.
</blockquote></details>

@rhmtrz  this review is not solved.

**Review by rhmtrz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tigerscave/ada-firebase-auth/25)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @tadaniya)

___
*[src/components/anonymatter/my-account/dashboard-profile.js, line 2 at r1](https://reviewable.io/reviews/tigerscave/ada-firebase-auth/25#-LhjPaeS754Ax1AUdB3b:-LhjkOfR0txkHZoJqdIQ:b-896fix) ([raw file](https://github.com/tigerscave/ada-firebase-auth/blob/0b31a8f54b7dc6dbd78b44e8ba6c1242932b7c9f/src/components/anonymatter/my-account/dashboard-profile.js#L2)):*
<details><summary><i>Previously, tadaniya wrote…</i></summary><blockquote>

@rhmtrz  this review is not solved.
</blockquote></details>

Done.

**Review by azamiya — APPROVED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/tigerscave/ada-firebase-auth/25)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by azamiya — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/tigerscave/ada-firebase-auth/25)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
