### PR TITLE
feat: edit profile

### PR DESCRIPTION
**Pull request by rhmtrz**
This change is [Reviewable](https://reviewable.io/reviews/tigerscave/ada-firebase-auth/7)

### CODE REVIEW

**Review by azamiya — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/tigerscave/ada-firebase-auth/7)* status: all files reviewed, 2 unresolved discussions (waiting on @rhmtrz)

___
*[src/components/my-account/edit-user-profile.js, line 10 at r1](https://reviewable.io/reviews/tigerscave/ada-firebase-auth/7#-Lfnpnct-dFfhMTpWZUz:-Lfnpnct-dFfhMTpWZV-:b8ql1gm) ([raw file](https://github.com/tigerscave/ada-firebase-auth/blob/c8a63a53c5a55cfeb07e2d753794ff39b96836d8/src/components/my-account/edit-user-profile.js#L10)):*
> ```JavaScript
>   const [displayName, onChangeName] = useState("");
>   const [photoURL, onChangePhoto] = useState("");
>   const [isToggleModal, onToggleModal] = useState(false);
> ```

`isModalShown` is better. `isToggleModal` is a bit strange.
also, `onToggleModal` is not good. just `toggleModal` is enough.
___
*[src/components/my-account/edit-user-profile.js, line 27 at r1](https://reviewable.io/reviews/tigerscave/ada-firebase-auth/7#-Lfnq7Y6BJaHWjolQzVa:-Lfnq7Y76Z9c2m8d8Lp8:b1y3lcx) ([raw file](https://github.com/tigerscave/ada-firebase-auth/blob/c8a63a53c5a55cfeb07e2d753794ff39b96836d8/src/components/my-account/edit-user-profile.js#L27)):*
> ```JavaScript
>               onChange={e => onChangePhoto(e.target.value)}
>             />
>             {/*<button id="uploadPhoto">Upload Photo</button>*/}
> ```

delete if you not need this line.

**Review by rhmtrz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tigerscave/ada-firebase-auth/7)* status: 4 of 10 files reviewed, 2 unresolved discussions (waiting on @tadaniya)

___
*[src/components/my-account/edit-user-profile.js, line 10 at r1](https://reviewable.io/reviews/tigerscave/ada-firebase-auth/7#-Lfnpnct-dFfhMTpWZUz:-LfxDi6xCAFZB8TmtLL_:b-896fix) ([raw file](https://github.com/tigerscave/ada-firebase-auth/blob/c8a63a53c5a55cfeb07e2d753794ff39b96836d8/src/components/my-account/edit-user-profile.js#L10)):*
<details><summary><i>Previously, tadaniya wrote…</i></summary><blockquote>

`isModalShown` is better. `isToggleModal` is a bit strange.
also, `onToggleModal` is not good. just `toggleModal` is enough.
</blockquote></details>

Done.
___
*[src/components/my-account/edit-user-profile.js, line 27 at r1](https://reviewable.io/reviews/tigerscave/ada-firebase-auth/7#-Lfnq7Y6BJaHWjolQzVa:-LfxDiNp-LS5dnmxw_o5:b-896fix) ([raw file](https://github.com/tigerscave/ada-firebase-auth/blob/c8a63a53c5a55cfeb07e2d753794ff39b96836d8/src/components/my-account/edit-user-profile.js#L27)):*
<details><summary><i>Previously, tadaniya wrote…</i></summary><blockquote>

delete if you not need this line.
</blockquote></details>

Done.

**Review by azamiya — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/tigerscave/ada-firebase-auth/7)* status: all files reviewed, 1 unresolved discussion (waiting on @rhmtrz)

___
*[src/pages/twitter/post-tweet.js, line 2 at r2](https://reviewable.io/reviews/tigerscave/ada-firebase-auth/7#-LfxDy-r1HimUQavjn-X:-LfxDy-s-7a3ksuSFJch:b-6niaqe) ([raw file](https://github.com/tigerscave/ada-firebase-auth/blob/af236ce6e8c54e41feac7ad0393f286c197b4b0f/src/pages/twitter/post-tweet.js#L2)):*
> ```JavaScript
> import React, { useState } from "react";
> import { createTweet } from "../../redux/reducers/post-tweet";
> ```

`post-tweet` naming is not good. just `tweet` is fine.

**Review by azamiya — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tigerscave/ada-firebase-auth/7)* status: all files reviewed, 2 unresolved discussions (waiting on @rhmtrz)

___
*[src/pages/twitter/post-tweet.js, line 13 at r2](https://reviewable.io/reviews/tigerscave/ada-firebase-auth/7#-LfxF5pJAScOVPvALHCO:-LfxF5pJAScOVPvALHCP:b2nh8oq) ([raw file](https://github.com/tigerscave/ada-firebase-auth/blob/af236ce6e8c54e41feac7ad0393f286c197b4b0f/src/pages/twitter/post-tweet.js#L13)):*
> ```JavaScript
>       <h1>Post Tweet</h1>
>       <input
>         placeholder="password"
> ```

???

**Review by azamiya — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tigerscave/ada-firebase-auth/7)* status: all files reviewed, 3 unresolved discussions (waiting on @rhmtrz)

___
*[src/pages/twitter/post-tweet.js, line 18 at r2](https://reviewable.io/reviews/tigerscave/ada-firebase-auth/7#-LfxFH-z0M9REAsTdRDK:-LfxFH-z0M9REAsTdRDL:b-1zxjgu) ([raw file](https://github.com/tigerscave/ada-firebase-auth/blob/af236ce6e8c54e41feac7ad0393f286c197b4b0f/src/pages/twitter/post-tweet.js#L18)):*
> ```
> onCreateTweetPost
> ```

mmm
just onPostButtonClicked is better.

**Review by rhmtrz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tigerscave/ada-firebase-auth/7)* status: 6 of 10 files reviewed, 3 unresolved discussions (waiting on @tadaniya)

___
*[src/pages/twitter/post-tweet.js, line 2 at r2](https://reviewable.io/reviews/tigerscave/ada-firebase-auth/7#-LfxDy-r1HimUQavjn-X:-LfxGDBNB6bSTyENyG19:b-896fix) ([raw file](https://github.com/tigerscave/ada-firebase-auth/blob/af236ce6e8c54e41feac7ad0393f286c197b4b0f/src/pages/twitter/post-tweet.js#L2)):*
<details><summary><i>Previously, tadaniya wrote…</i></summary><blockquote>

`post-tweet` naming is not good. just `tweet` is fine.
</blockquote></details>

Done.
___
*[src/pages/twitter/post-tweet.js, line 13 at r2](https://reviewable.io/reviews/tigerscave/ada-firebase-auth/7#-LfxF5pJAScOVPvALHCO:-LfxIBeUC_KTyQKyN_fU:b-896fix) ([raw file](https://github.com/tigerscave/ada-firebase-auth/blob/af236ce6e8c54e41feac7ad0393f286c197b4b0f/src/pages/twitter/post-tweet.js#L13)):*
<details><summary><i>Previously, tadaniya wrote…</i></summary><blockquote>

???
</blockquote></details>

Done.
___
*[src/pages/twitter/post-tweet.js, line 18 at r2](https://reviewable.io/reviews/tigerscave/ada-firebase-auth/7#-LfxFH-z0M9REAsTdRDK:-LfxGXFI2cx71T-UUy9i:b-896fix) ([raw file](https://github.com/tigerscave/ada-firebase-auth/blob/af236ce6e8c54e41feac7ad0393f286c197b4b0f/src/pages/twitter/post-tweet.js#L18)):*
<details><summary><i>Previously, tadaniya wrote…</i></summary><blockquote>

> ```
> onCreateTweetPost
> ```

mmm
just onPostButtonClicked is better.
</blockquote></details>

Done.

**Review by azamiya — APPROVED** [review]
> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/tigerscave/ada-firebase-auth/7)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
