### PR TITLE
WIP: update user profile

### PR DESCRIPTION
**Pull request by azamiya**
This change is [Reviewable](https://reviewable.io/reviews/tigerscave/ada-firebase-auth/10)

### CODE REVIEW

**Review by azamiya — COMMENTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/tigerscave/ada-firebase-auth/10)* status: all files reviewed, 4 unresolved discussions

___
*[src/components/my-account/update-use-profile.js, line 10 at r1](https://reviewable.io/reviews/tigerscave/ada-firebase-auth/10#-LgMMb7z6oWM_bUJ1YXk:-LgMMb7z6oWM_bUJ1YXl:b-h7y0kg) ([raw file](https://github.com/tigerscave/ada-firebase-auth/blob/9e1a5fd5072a80f803a0b8adc80f7bb1819ec800/src/components/my-account/update-use-profile.js#L10)):*
> ```JavaScript
>     super(props);
>     this.state = {
>       browsPhoto: "",
> ```

what is the meaning of `browsPhoto` ?
___
*[src/components/my-account/update-use-profile.js, line 15 at r1](https://reviewable.io/reviews/tigerscave/ada-firebase-auth/10#-LgMMiYW5qNtSLL_437I:-LgMMiYW5qNtSLL_437J:bonek65) ([raw file](https://github.com/tigerscave/ada-firebase-auth/blob/9e1a5fd5072a80f803a0b8adc80f7bb1819ec800/src/components/my-account/update-use-profile.js#L15)):*
> ```JavaScript
>     };
> 
>     this.onBrowsPhoto = e => {
> ```

what is the meaning of `onBrowsPhoto` ? I can not understand.
___
*[src/components/my-account/update-use-profile.js, line 62 at r1](https://reviewable.io/reviews/tigerscave/ada-firebase-auth/10#-LgMNC1h8OCpvWNGsXIq:-LgMNC1h8OCpvWNGsXIr:b-c06w9l) ([raw file](https://github.com/tigerscave/ada-firebase-auth/blob/9e1a5fd5072a80f803a0b8adc80f7bb1819ec800/src/components/my-account/update-use-profile.js#L62)):*
> ```JavaScript
> const mapDispatchToProps = dispatch => {
>   return {
>     onUploadUserProfile: image => dispatch(updateUserProfile(image))
> ```

why you put `on` prefix ?
`onUploadButtonClicked` is better ?
___
*[src/pages/my-account.js, line 6 at r1](https://reviewable.io/reviews/tigerscave/ada-firebase-auth/10#-LgMMujP0J3OywMLsEGT:-LgMMujP0J3OywMLsEGU:b-edt944) ([raw file](https://github.com/tigerscave/ada-firebase-auth/blob/9e1a5fd5072a80f803a0b8adc80f7bb1819ec800/src/pages/my-account.js#L6)):*
> ```JavaScript
> import ConfirmDeleteModal from "../components/my-account/delete-modal";
> import EditProfile from "../components/my-account/edit-user-profile";
> import UpdateUserProfile from "../components/my-account/update-use-profile";
> ```

what is `update-use-profile` ?
not `update-user-profile` ???

**Review by rhmtrz — APPROVED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/tigerscave/ada-firebase-auth/10)* status: all files reviewed, 4 unresolved discussions

**Review by azamiya — COMMENTED** [review]
> Reviewed 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/tigerscave/ada-firebase-auth/10)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @rhmtrz and @tadaniya)

**Review by azamiya — COMMENTED** [review]
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/tigerscave/ada-firebase-auth/10)* status: all files reviewed, 1 unresolved discussion

**Review by azamiya — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/tigerscave/ada-firebase-auth/10)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
