### PR TITLE
feat: tweet with image

### PR DESCRIPTION
**Pull request by rhmtrz**
This change is [Reviewable](https://reviewable.io/reviews/tigerscave/ada-firebase-auth/11)

### CODE REVIEW

**Review by azamiya — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/tigerscave/ada-firebase-auth/11)* status: all files reviewed, 3 unresolved discussions (waiting on @rhmtrz)

___
*[src/pages/twitter/post-tweet.js, line 16 at r1](https://reviewable.io/reviews/tigerscave/ada-firebase-auth/11#-LgeJJGy3IV1H5gLrRix:-LgeJJGy3IV1H5gLrRiy:brd4l77) ([raw file](https://github.com/tigerscave/ada-firebase-auth/blob/ddf0cd6b84f34eecfed268517fa6295c5387154d/src/pages/twitter/post-tweet.js#L16)):*
> ```JavaScript
>     };
> 
>     this.onGetTweetImage = e => {
> ```

`onGetTweetImage` ....  `onTweetImageChange` is better
___
*[src/pages/twitter/post-tweet.js, line 23 at r1](https://reviewable.io/reviews/tigerscave/ada-firebase-auth/11#-LgeJRVY5fHQe9fT0-nk:-LgeJRVY5fHQe9fT0-nl:boo94uk) ([raw file](https://github.com/tigerscave/ada-firebase-auth/blob/ddf0cd6b84f34eecfed268517fa6295c5387154d/src/pages/twitter/post-tweet.js#L23)):*
> ```JavaScript
>     };
> 
>     this.onGetTweetText = e => {
> ```

`onGetTweet` .... `onTweetTextChange` is better
___
*[src/redux/middlewares/tweetMiddleware.js, line 37 at r1](https://reviewable.io/reviews/tigerscave/ada-firebase-auth/11#-LgeJmlX1hLUtnyTUhCj:-LgeJmlX1hLUtnyTUhCk:bgeamvz) ([raw file](https://github.com/tigerscave/ada-firebase-auth/blob/ddf0cd6b84f34eecfed268517fa6295c5387154d/src/redux/middlewares/tweetMiddleware.js#L37)):*
> ```JavaScript
>     } else {
>       firebase.auth().onAuthStateChanged(user => {
>         db.collection("tweets")
> ```

you can use helper method in here.

**Review by rhmtrz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tigerscave/ada-firebase-auth/11)* status: all files reviewed, 3 unresolved discussions (waiting on @tadaniya)

___
*[src/pages/twitter/post-tweet.js, line 16 at r1](https://reviewable.io/reviews/tigerscave/ada-firebase-auth/11#-LgeJJGy3IV1H5gLrRix:-LgeMvQN9nHNarOC59fd:b-896fix) ([raw file](https://github.com/tigerscave/ada-firebase-auth/blob/ddf0cd6b84f34eecfed268517fa6295c5387154d/src/pages/twitter/post-tweet.js#L16)):*
<details><summary><i>Previously, tadaniya wrote…</i></summary><blockquote>

`onGetTweetImage` ....  `onTweetImageChange` is better
</blockquote></details>

Done.
___
*[src/pages/twitter/post-tweet.js, line 23 at r1](https://reviewable.io/reviews/tigerscave/ada-firebase-auth/11#-LgeJRVY5fHQe9fT0-nk:-LgeMvkXCk0xSHhiUx_I:b-896fix) ([raw file](https://github.com/tigerscave/ada-firebase-auth/blob/ddf0cd6b84f34eecfed268517fa6295c5387154d/src/pages/twitter/post-tweet.js#L23)):*
<details><summary><i>Previously, tadaniya wrote…</i></summary><blockquote>

`onGetTweet` .... `onTweetTextChange` is better
</blockquote></details>

Done.
___
*[src/redux/middlewares/tweetMiddleware.js, line 37 at r1](https://reviewable.io/reviews/tigerscave/ada-firebase-auth/11#-LgeJmlX1hLUtnyTUhCj:-LgeQfBa7Piz2X16d-wf:b-896fix) ([raw file](https://github.com/tigerscave/ada-firebase-auth/blob/ddf0cd6b84f34eecfed268517fa6295c5387154d/src/redux/middlewares/tweetMiddleware.js#L37)):*
<details><summary><i>Previously, tadaniya wrote…</i></summary><blockquote>

you can use helper method in here.
</blockquote></details>

Done.

**Review by azamiya — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/tigerscave/ada-firebase-auth/11)* status: all files reviewed, 2 unresolved discussions (waiting on @rhmtrz and @tadaniya)

___
*[src/redux/middlewares/tweetMiddleware.js, line 5 at r2](https://reviewable.io/reviews/tigerscave/ada-firebase-auth/11#-LgeowQiBVbxGfZzWOCk:-LgeowQj5hgPPO9PL7wD:ben9jy6) ([raw file](https://github.com/tigerscave/ada-firebase-auth/blob/b98aee3d3cd7750c31b4cd38f6bee9c743c89c0c/src/redux/middlewares/tweetMiddleware.js#L5)):*
> ```JavaScript
> import firebase from "firebase/app";
> import "firebase/firestore";
> // import { push } from "connected-react-router";
> ```

remove unnecessary comment

**Review by azamiya — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/tigerscave/ada-firebase-auth/11)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
